word(["a", "a", "l"]).
word(["a", "a", "m"]).
word(["a", "b", "a"]).
word(["a", "b", "b"]).
word(["A", "b", "e"]).
word(["A", "b", "o"]).
word(["A", "b", "u"]).
word(["a", "b", "u"]).
word(["a", "b", "y"]).
word(["a", "c", "e"]).
word(["a", "c", "h"]).
word(["a", "c", "t"]).
word(["A", "d", "a"]).
word(["a", "d", "d"]).
word(["A", "d", "e"]).
word(["a", "d", "e"]).
word(["a", "d", "o"]).
word(["a", "d", "y"]).
word(["a", "d", "z"]).
word(["a", "e", "r"]).
word(["a", "e", "s"]).
word(["a", "f", "t"]).
word(["a", "g", "a"]).
word(["a", "g", "e"]).
word(["a", "g", "o"]).
word(["a", "g", "y"]).
word(["a", "h", "a"]).
word(["a", "h", "o"]).
word(["A", "h", "t"]).
word(["a", "h", "u"]).
word(["a", "i", "d"]).
word(["a", "i", "l"]).
word(["a", "i", "m"]).
word(["a", "i", "r"]).
word(["a", "i", "t"]).
word(["A", "i", "x"]).
word(["A", "k", "a"]).
word(["a", "k", "a"]).
word(["a", "k", "e"]).
word(["a", "k", "o"]).
word(["a", "k", "u"]).
word(["a", "l", "a"]).
word(["A", "l", "b"]).
word(["a", "l", "b"]).
word(["a", "l", "e"]).
word(["A", "l", "f"]).
word(["a", "l", "f"]).
word(["a", "l", "k"]).
word(["a", "l", "l"]).
word(["a", "l", "n"]).
word(["a", "l", "o"]).
word(["a", "l", "p"]).
word(["a", "l", "t"]).
word(["a", "l", "y"]).
word(["a", "m", "a"]).
word(["a", "m", "e"]).
word(["A", "m", "i"]).
word(["a", "m", "i"]).
word(["a", "m", "t"]).
word(["A", "m", "y"]).
word(["a", "m", "y"]).
word(["A", "n", "a"]).
word(["a", "n", "a"]).
word(["a", "n", "d"]).
word(["a", "n", "i"]).
word(["A", "n", "n"]).
word(["a", "n", "n"]).
word(["a", "n", "t"]).
word(["a", "n", "y"]).
word(["a", "p", "a"]).
word(["a", "p", "e"]).
word(["a", "p", "t"]).
word(["a", "r", "a"]).
word(["a", "r", "c"]).
word(["a", "r", "e"]).
word(["a", "r", "k"]).
word(["a", "r", "m"]).
word(["a", "r", "n"]).
word(["A", "r", "o"]).
word(["A", "r", "t"]).
word(["a", "r", "t"]).
word(["a", "r", "u"]).
word(["a", "r", "x"]).
word(["a", "r", "y"]).
word(["A", "s", "a"]).
word(["a", "s", "e"]).
word(["a", "s", "h"]).
word(["a", "s", "k"]).
word(["a", "s", "p"]).
word(["a", "s", "s"]).
word(["a", "s", "t"]).
word(["A", "t", "a"]).
word(["a", "t", "e"]).
word(["A", "t", "i"]).
word(["a", "u", "h"]).
word(["A", "u", "k"]).
word(["a", "u", "k"]).
word(["a", "u", "m"]).
word(["A", "u", "s"]).
word(["a", "v", "a"]).
word(["A", "v", "e"]).
word(["a", "v", "e"]).
word(["a", "v", "o"]).
word(["a", "w", "a"]).
word(["a", "w", "d"]).
word(["a", "w", "e"]).
word(["a", "w", "l"]).
word(["a", "w", "n"]).
word(["a", "x", "e"]).
word(["a", "y", "e"]).
word(["a", "y", "u"]).
word(["a", "z", "o"]).
word(["b", "a", "a"]).
word(["B", "a", "b"]).
word(["b", "a", "c"]).
word(["b", "a", "d"]).
word(["b", "a", "e"]).
word(["b", "a", "g"]).
word(["b", "a", "h"]).
word(["B", "a", "l"]).
word(["b", "a", "l"]).
word(["b", "a", "m"]).
word(["B", "a", "n"]).
word(["b", "a", "n"]).
word(["b", "a", "p"]).
word(["b", "a", "r"]).
word(["b", "a", "s"]).
word(["B", "a", "t"]).
word(["b", "a", "t"]).
word(["b", "a", "w"]).
word(["b", "a", "y"]).
word(["B", "e", "a"]).
word(["b", "e", "d"]).
word(["B", "e", "e"]).
word(["b", "e", "e"]).
word(["b", "e", "g"]).
word(["B", "e", "l"]).
word(["b", "e", "l"]).
word(["B", "e", "n"]).
word(["b", "e", "n"]).
word(["b", "e", "r"]).
word(["b", "e", "s"]).
word(["b", "e", "t"]).
word(["b", "e", "y"]).
word(["b", "i", "b"]).
word(["b", "i", "d"]).
word(["b", "i", "g"]).
word(["B", "i", "m"]).
word(["b", "i", "n"]).
word(["b", "i", "s"]).
word(["b", "i", "t"]).
word(["b", "i", "z"]).
word(["b", "l", "o"]).
word(["b", "o", "a"]).
word(["B", "o", "b"]).
word(["b", "o", "b"]).
word(["b", "o", "d"]).
word(["b", "o", "g"]).
word(["b", "o", "m"]).
word(["B", "o", "n"]).
word(["b", "o", "n"]).
word(["b", "o", "o"]).
word(["b", "o", "p"]).
word(["b", "o", "r"]).
word(["B", "o", "s"]).
word(["b", "o", "t"]).
word(["b", "o", "w"]).
word(["b", "o", "y"]).
word(["b", "r", "a"]).
word(["b", "u", "b"]).
word(["B", "u", "d"]).
word(["b", "u", "d"]).
word(["b", "u", "g"]).
word(["b", "u", "m"]).
word(["b", "u", "n"]).
word(["b", "u", "r"]).
word(["b", "u", "s"]).
word(["b", "u", "t"]).
word(["b", "u", "y"]).
word(["b", "y", "e"]).
word(["c", "a", "b"]).
word(["c", "a", "d"]).
word(["c", "a", "g"]).
word(["c", "a", "l"]).
word(["c", "a", "m"]).
word(["c", "a", "n"]).
word(["c", "a", "p"]).
word(["c", "a", "r"]).
word(["C", "a", "t"]).
word(["c", "a", "t"]).
word(["c", "a", "w"]).
word(["c", "a", "y"]).
word(["c", "e", "e"]).
word(["c", "e", "p"]).
word(["c", "h", "a"]).
word(["c", "h", "e"]).
word(["c", "h", "i"]).
word(["c", "h", "o"]).
word(["C", "i", "d"]).
word(["c", "i", "g"]).
word(["c", "i", "t"]).
word(["c", "l", "y"]).
word(["c", "o", "b"]).
word(["c", "o", "d"]).
word(["c", "o", "e"]).
word(["c", "o", "g"]).
word(["c", "o", "l"]).
word(["c", "o", "n"]).
word(["c", "o", "o"]).
word(["c", "o", "p"]).
word(["c", "o", "r"]).
word(["c", "o", "s"]).
word(["c", "o", "t"]).
word(["c", "o", "w"]).
word(["c", "o", "x"]).
word(["c", "o", "y"]).
word(["c", "o", "z"]).
word(["c", "r", "o"]).
word(["c", "r", "y"]).
word(["c", "u", "b"]).
word(["c", "u", "d"]).
word(["c", "u", "e"]).
word(["c", "u", "m"]).
word(["c", "u", "p"]).
word(["c", "u", "r"]).
word(["c", "u", "t"]).
word(["c", "w", "m"]).
word(["c", "y", "p"]).
word(["d", "a", "b"]).
word(["d", "a", "d"]).
word(["d", "a", "e"]).
word(["d", "a", "g"]).
word(["d", "a", "h"]).
word(["d", "a", "k"]).
word(["d", "a", "l"]).
word(["d", "a", "m"]).
word(["D", "a", "n"]).
word(["d", "a", "n"]).
word(["d", "a", "o"]).
word(["d", "a", "p"]).
word(["d", "a", "r"]).
word(["d", "a", "s"]).
word(["d", "a", "w"]).
word(["d", "a", "y"]).
word(["D", "e", "b"]).
word(["d", "e", "b"]).
word(["d", "e", "e"]).
word(["d", "e", "g"]).
word(["D", "e", "l"]).
word(["d", "e", "n"]).
word(["d", "e", "v"]).
word(["d", "e", "w"]).
word(["d", "e", "y"]).
word(["d", "h", "a"]).
word(["d", "h", "u"]).
word(["d", "i", "b"]).
word(["d", "i", "d"]).
word(["d", "i", "e"]).
word(["d", "i", "g"]).
word(["d", "i", "m"]).
word(["d", "i", "n"]).
word(["d", "i", "p"]).
word(["d", "i", "s"]).
word(["d", "i", "t"]).
word(["d", "i", "v"]).
word(["D", "o", "b"]).
word(["d", "o", "b"]).
word(["d", "o", "c"]).
word(["d", "o", "d"]).
word(["d", "o", "e"]).
word(["d", "o", "g"]).
word(["D", "o", "l"]).
word(["d", "o", "m"]).
word(["D", "o", "n"]).
word(["d", "o", "n"]).
word(["d", "o", "p"]).
word(["D", "o", "r"]).
word(["d", "o", "r"]).
word(["d", "o", "s"]).
word(["D", "o", "t"]).
word(["d", "o", "t"]).
word(["d", "o", "w"]).
word(["d", "r", "y"]).
word(["d", "u", "b"]).
word(["d", "u", "d"]).
word(["d", "u", "e"]).
word(["d", "u", "g"]).
word(["d", "u", "m"]).
word(["d", "u", "n"]).
word(["d", "u", "o"]).
word(["d", "u", "p"]).
word(["d", "u", "x"]).
word(["d", "y", "e"]).
word(["e", "a", "n"]).
word(["e", "a", "r"]).
word(["e", "a", "t"]).
word(["e", "b", "b"]).
word(["e", "d", "h"]).
word(["E", "d", "o"]).
word(["e", "e", "l"]).
word(["e", "e", "r"]).
word(["e", "f", "t"]).
word(["e", "g", "g"]).
word(["e", "g", "o"]).
word(["e", "k", "e"]).
word(["e", "l", "b"]).
word(["e", "l", "d"]).
word(["e", "l", "f"]).
word(["E", "l", "i"]).
word(["e", "l", "k"]).
word(["e", "l", "l"]).
word(["e", "l", "m"]).
word(["e", "l", "s"]).
word(["e", "l", "t"]).
word(["e", "m", "e"]).
word(["E", "m", "m"]).
word(["e", "m", "u"]).
word(["e", "n", "d"]).
word(["e", "n", "s"]).
word(["e", "o", "n"]).
word(["e", "r", "a"]).
word(["e", "r", "d"]).
word(["e", "r", "e"]).
word(["e", "r", "g"]).
word(["e", "r", "r"]).
word(["e", "r", "s"]).
word(["e", "s", "s"]).
word(["e", "t", "a"]).
word(["E", "v", "a"]).
word(["E", "v", "e"]).
word(["e", "v", "e"]).
word(["E", "w", "e"]).
word(["e", "w", "e"]).
word(["e", "y", "e"]).
word(["e", "y", "n"]).
word(["f", "a", "d"]).
word(["f", "a", "e"]).
word(["f", "a", "g"]).
word(["f", "a", "m"]).
word(["F", "a", "n"]).
word(["f", "a", "n"]).
word(["f", "a", "r"]).
word(["f", "a", "t"]).
word(["F", "a", "y"]).
word(["f", "a", "y"]).
word(["f", "e", "d"]).
word(["f", "e", "e"]).
word(["f", "e", "i"]).
word(["f", "e", "n"]).
word(["f", "e", "t"]).
word(["f", "e", "u"]).
word(["f", "e", "w"]).
word(["f", "e", "y"]).
word(["f", "e", "z"]).
word(["f", "i", "b"]).
word(["f", "i", "d"]).
word(["f", "i", "e"]).
word(["f", "i", "g"]).
word(["F", "i", "n"]).
word(["f", "i", "n"]).
word(["f", "i", "p"]).
word(["f", "i", "r"]).
word(["f", "i", "t"]).
word(["f", "i", "x"]).
word(["F", "l", "o"]).
word(["f", "l", "u"]).
word(["f", "l", "y"]).
word(["f", "o", "b"]).
word(["f", "o", "d"]).
word(["f", "o", "e"]).
word(["f", "o", "g"]).
word(["F", "o", "n"]).
word(["f", "o", "o"]).
word(["f", "o", "p"]).
word(["F", "o", "r"]).
word(["f", "o", "r"]).
word(["f", "o", "t"]).
word(["f", "o", "u"]).
word(["f", "o", "w"]).
word(["f", "o", "x"]).
word(["f", "o", "y"]).
word(["f", "r", "a"]).
word(["f", "r", "o"]).
word(["f", "r", "y"]).
word(["f", "u", "b"]).
word(["f", "u", "d"]).
word(["f", "u", "m"]).
word(["f", "u", "n"]).
word(["F", "u", "r"]).
word(["f", "u", "r"]).
word(["f", "u", "t"]).
word(["g", "a", "b"]).
word(["G", "a", "d"]).
word(["g", "a", "d"]).
word(["g", "a", "g"]).
word(["g", "a", "j"]).
word(["g", "a", "l"]).
word(["g", "a", "m"]).
word(["g", "a", "n"]).
word(["g", "a", "p"]).
word(["g", "a", "r"]).
word(["g", "a", "s"]).
word(["g", "a", "t"]).
word(["g", "a", "u"]).
word(["g", "a", "w"]).
word(["g", "a", "y"]).
word(["g", "a", "z"]).
word(["G", "e", "d"]).
word(["g", "e", "d"]).
word(["G", "e", "e"]).
word(["g", "e", "e"]).
word(["g", "e", "l"]).
word(["g", "e", "m"]).
word(["g", "e", "n"]).
word(["g", "e", "o"]).
word(["g", "e", "r"]).
word(["G", "e", "s"]).
word(["g", "e", "t"]).
word(["g", "e", "y"]).
word(["g", "e", "z"]).
word(["G", "i", "b"]).
word(["g", "i", "b"]).
word(["g", "i", "d"]).
word(["g", "i", "e"]).
word(["g", "i", "f"]).
word(["g", "i", "g"]).
word(["G", "i", "l"]).
word(["g", "i", "m"]).
word(["g", "i", "n"]).
word(["g", "i", "o"]).
word(["g", "i", "p"]).
word(["g", "i", "t"]).
word(["g", "n", "u"]).
word(["g", "o", "a"]).
word(["g", "o", "b"]).
word(["G", "o", "d"]).
word(["g", "o", "d"]).
word(["g", "o", "g"]).
word(["g", "o", "i"]).
word(["g", "o", "l"]).
word(["g", "o", "n"]).
word(["g", "o", "o"]).
word(["G", "o", "r"]).
word(["g", "o", "r"]).
word(["g", "o", "s"]).
word(["g", "o", "t"]).
word(["g", "o", "y"]).
word(["g", "r", "a"]).
word(["g", "r", "r"]).
word(["g", "u", "d"]).
word(["g", "u", "e"]).
word(["g", "u", "l"]).
word(["G", "u", "m"]).
word(["g", "u", "m"]).
word(["g", "u", "n"]).
word(["g", "u", "p"]).
word(["g", "u", "r"]).
word(["G", "u", "s"]).
word(["g", "u", "t"]).
word(["G", "u", "y"]).
word(["g", "u", "y"]).
word(["g", "u", "z"]).
word(["g", "y", "m"]).
word(["g", "y", "n"]).
word(["g", "y", "p"]).
word(["h", "a", "d"]).
word(["h", "a", "g"]).
word(["h", "a", "h"]).
word(["h", "a", "k"]).
word(["H", "a", "l"]).
word(["h", "a", "m"]).
word(["h", "a", "n"]).
word(["h", "a", "o"]).
word(["h", "a", "p"]).
word(["h", "a", "t"]).
word(["h", "a", "u"]).
word(["h", "a", "w"]).
word(["h", "a", "y"]).
word(["h", "e", "i"]).
word(["h", "e", "m"]).
word(["h", "e", "n"]).
word(["h", "e", "p"]).
word(["h", "e", "r"]).
word(["h", "e", "t"]).
word(["h", "e", "w"]).
word(["h", "e", "x"]).
word(["h", "e", "y"]).
word(["h", "i", "a"]).
word(["h", "i", "c"]).
word(["h", "i", "e"]).
word(["h", "i", "m"]).
word(["h", "i", "n"]).
word(["h", "i", "p"]).
word(["h", "i", "s"]).
word(["h", "i", "t"]).
word(["h", "o", "b"]).
word(["h", "o", "d"]).
word(["h", "o", "e"]).
word(["h", "o", "g"]).
word(["h", "o", "i"]).
word(["H", "o", "n"]).
word(["h", "o", "p"]).
word(["h", "o", "t"]).
word(["h", "o", "w"]).
word(["h", "o", "x"]).
word(["h", "o", "y"]).
word(["H", "s", "i"]).
word(["h", "u", "b"]).
word(["h", "u", "d"]).
word(["h", "u", "e"]).
word(["h", "u", "g"]).
word(["h", "u", "h"]).
word(["H", "u", "i"]).
word(["H", "u", "k"]).
word(["h", "u", "m"]).
word(["H", "u", "n"]).
word(["h", "u", "p"]).
word(["h", "u", "t"]).
word(["H", "w", "a"]).
word(["h", "y", "p"]).
word(["I", "a", "n"]).
word(["i", "a", "o"]).
word(["i", "b", "a"]).
word(["I", "b", "o"]).
word(["i", "c", "e"]).
word(["i", "c", "h"]).
word(["i", "c", "y"]).
word(["I", "d", "a"]).
word(["i", "d", "e"]).
word(["I", "d", "o"]).
word(["i", "f", "e"]).
word(["i", "h", "i"]).
word(["I", "j", "o"]).
word(["I", "k", "e"]).
word(["I", "l", "a"]).
word(["i", "l", "k"]).
word(["i", "l", "l"]).
word(["I", "m", "a"]).
word(["i", "m", "i"]).
word(["i", "m", "p"]).
word(["i", "m", "u"]).
word(["I", "n", "d"]).
word(["I", "n", "g"]).
word(["i", "n", "g"]).
word(["i", "n", "k"]).
word(["i", "n", "n"]).
word(["I", "n", "o"]).
word(["i", "o", "n"]).
word(["I", "r", "a"]).
word(["i", "r", "e"]).
word(["i", "r", "k"]).
word(["i", "s", "m"]).
word(["i", "s", "o"]).
word(["i", "s", "t"]).
word(["I", "t", "a"]).
word(["I", "t", "o"]).
word(["i", "t", "s"]).
word(["i", "v", "a"]).
word(["i", "v", "y"]).
word(["i", "w", "a"]).
word(["i", "y", "o"]).
word(["j", "a", "b"]).
word(["j", "a", "g"]).
word(["J", "a", "m"]).
word(["j", "a", "m"]).
word(["J", "a", "n"]).
word(["J", "a", "p"]).
word(["j", "a", "p"]).
word(["j", "a", "r"]).
word(["J", "a", "t"]).
word(["j", "a", "w"]).
word(["J", "a", "y"]).
word(["j", "a", "y"]).
word(["j", "e", "d"]).
word(["J", "e", "f"]).
word(["J", "e", "m"]).
word(["j", "e", "t"]).
word(["J", "e", "w"]).
word(["j", "i", "b"]).
word(["j", "i", "g"]).
word(["J", "i", "m"]).
word(["J", "i", "n"]).
word(["J", "o", "b"]).
word(["j", "o", "b"]).
word(["J", "o", "e"]).
word(["j", "o", "e"]).
word(["j", "o", "g"]).
word(["J", "o", "n"]).
word(["J", "o", "s"]).
word(["j", "o", "t"]).
word(["j", "o", "w"]).
word(["j", "o", "y"]).
word(["j", "u", "d"]).
word(["j", "u", "g"]).
word(["J", "u", "n"]).
word(["J", "u", "r"]).
word(["j", "u", "t"]).
word(["K", "a", "f"]).
word(["k", "a", "i"]).
word(["K", "a", "j"]).
word(["k", "a", "n"]).
word(["k", "a", "t"]).
word(["K", "a", "w"]).
word(["K", "a", "y"]).
word(["k", "a", "y"]).
word(["k", "e", "a"]).
word(["k", "e", "b"]).
word(["k", "e", "d"]).
word(["K", "e", "e"]).
word(["k", "e", "f"]).
word(["k", "e", "g"]).
word(["K", "e", "n"]).
word(["k", "e", "n"]).
word(["k", "e", "p"]).
word(["K", "e", "r"]).
word(["k", "e", "t"]).
word(["k", "e", "x"]).
word(["k", "e", "y"]).
word(["K", "h", "a"]).
word(["k", "h", "u"]).
word(["k", "i", "l"]).
word(["K", "i", "m"]).
word(["k", "i", "m"]).
word(["k", "i", "n"]).
word(["k", "i", "p"]).
word(["K", "i", "t"]).
word(["k", "i", "t"]).
word(["k", "o", "a"]).
word(["k", "o", "b"]).
word(["k", "o", "i"]).
word(["K", "o", "l"]).
word(["k", "o", "n"]).
word(["k", "o", "p"]).
word(["k", "o", "r"]).
word(["k", "o", "s"]).
word(["k", "o", "u"]).
word(["K", "r", "a"]).
word(["k", "r", "a"]).
word(["K", "r", "u"]).
word(["K", "u", "a"]).
word(["K", "u", "i"]).
word(["k", "y", "l"]).
word(["K", "y", "u"]).
word(["l", "a", "b"]).
word(["l", "a", "c"]).
word(["l", "a", "d"]).
word(["l", "a", "g"]).
word(["L", "a", "i"]).
word(["l", "a", "i"]).
word(["L", "a", "k"]).
word(["l", "a", "k"]).
word(["l", "a", "m"]).
word(["l", "a", "n"]).
word(["L", "a", "o"]).
word(["l", "a", "p"]).
word(["L", "a", "r"]).
word(["l", "a", "r"]).
word(["l", "a", "s"]).
word(["l", "a", "t"]).
word(["l", "a", "w"]).
word(["l", "a", "x"]).
word(["l", "a", "y"]).
word(["L", "a", "z"]).
word(["L", "e", "a"]).
word(["l", "e", "a"]).
word(["l", "e", "d"]).
word(["L", "e", "e"]).
word(["l", "e", "e"]).
word(["l", "e", "g"]).
word(["l", "e", "i"]).
word(["l", "e", "k"]).
word(["L", "e", "n"]).
word(["L", "e", "o"]).
word(["L", "e", "r"]).
word(["L", "e", "s"]).
word(["l", "e", "t"]).
word(["l", "e", "u"]).
word(["l", "e", "v"]).
word(["L", "e", "w"]).
word(["l", "e", "w"]).
word(["L", "e", "x"]).
word(["l", "e", "y"]).
word(["l", "i", "d"]).
word(["l", "i", "e"]).
word(["L", "i", "f"]).
word(["l", "i", "m"]).
word(["L", "i", "n"]).
word(["l", "i", "n"]).
word(["l", "i", "p"]).
word(["l", "i", "s"]).
word(["l", "i", "t"]).
word(["L", "i", "v"]).
word(["L", "i", "z"]).
word(["L", "o", "a"]).
word(["l", "o", "a"]).
word(["l", "o", "b"]).
word(["l", "o", "d"]).
word(["l", "o", "f"]).
word(["l", "o", "g"]).
word(["l", "o", "o"]).
word(["l", "o", "p"]).
word(["L", "o", "t"]).
word(["l", "o", "t"]).
word(["L", "o", "u"]).
word(["l", "o", "w"]).
word(["l", "o", "x"]).
word(["l", "o", "y"]).
word(["L", "u", "c"]).
word(["l", "u", "e"]).
word(["L", "u", "g"]).
word(["l", "u", "g"]).
word(["L", "u", "i"]).
word(["L", "u", "m"]).
word(["l", "u", "m"]).
word(["L", "u", "o"]).
word(["L", "u", "r"]).
word(["l", "u", "t"]).
word(["l", "u", "x"]).
word(["L", "w", "o"]).
word(["l", "y", "e"]).
word(["l", "y", "s"]).
word(["M", "a", "b"]).
word(["M", "a", "c"]).
word(["m", "a", "c"]).
word(["m", "a", "d"]).
word(["m", "a", "e"]).
word(["m", "a", "g"]).
word(["M", "a", "h"]).
word(["m", "a", "l"]).
word(["M", "a", "m"]).
word(["m", "a", "n"]).
word(["m", "a", "o"]).
word(["m", "a", "p"]).
word(["M", "a", "r"]).
word(["m", "a", "r"]).
word(["m", "a", "s"]).
word(["M", "a", "t"]).
word(["m", "a", "t"]).
word(["m", "a", "u"]).
word(["m", "a", "w"]).
word(["M", "a", "x"]).
word(["M", "a", "y"]).
word(["m", "a", "y"]).
word(["M", "e", "g"]).
word(["m", "e", "l"]).
word(["m", "e", "m"]).
word(["m", "e", "n"]).
word(["M", "e", "o"]).
word(["M", "e", "r"]).
word(["M", "e", "s"]).
word(["m", "e", "t"]).
word(["M", "e", "v"]).
word(["m", "e", "w"]).
word(["m", "h", "o"]).
word(["m", "i", "b"]).
word(["m", "i", "d"]).
word(["m", "i", "g"]).
word(["M", "i", "l"]).
word(["m", "i", "l"]).
word(["m", "i", "m"]).
word(["m", "i", "n"]).
word(["m", "i", "r"]).
word(["m", "i", "x"]).
word(["m", "o", "b"]).
word(["M", "o", "d"]).
word(["M", "o", "e"]).
word(["m", "o", "g"]).
word(["M", "o", "i"]).
word(["M", "o", "n"]).
word(["m", "o", "n"]).
word(["m", "o", "o"]).
word(["m", "o", "p"]).
word(["m", "o", "r"]).
word(["m", "o", "t"]).
word(["m", "o", "u"]).
word(["m", "o", "w"]).
word(["m", "o", "y"]).
word(["M", "r", "s"]).
word(["M", "r", "u"]).
word(["m", "u", "d"]).
word(["m", "u", "g"]).
word(["m", "u", "m"]).
word(["m", "u", "n"]).
word(["M", "u", "s"]).
word(["m", "u", "x"]).
word(["M", "w", "a"]).
word(["M", "y", "a"]).
word(["n", "a", "a"]).
word(["n", "a", "b"]).
word(["n", "a", "e"]).
word(["n", "a", "g"]).
word(["n", "a", "k"]).
word(["n", "a", "m"]).
word(["N", "a", "n"]).
word(["n", "a", "n"]).
word(["n", "a", "p"]).
word(["n", "a", "r"]).
word(["n", "a", "t"]).
word(["n", "a", "w"]).
word(["n", "a", "y"]).
word(["n", "e", "a"]).
word(["n", "e", "b"]).
word(["N", "e", "d"]).
word(["n", "e", "e"]).
word(["n", "e", "f"]).
word(["n", "e", "i"]).
word(["n", "e", "o"]).
word(["N", "e", "p"]).
word(["n", "e", "p"]).
word(["N", "e", "t"]).
word(["n", "e", "t"]).
word(["n", "e", "w"]).
word(["n", "i", "b"]).
word(["n", "i", "d"]).
word(["n", "i", "g"]).
word(["n", "i", "l"]).
word(["n", "i", "m"]).
word(["N", "i", "p"]).
word(["n", "i", "p"]).
word(["n", "i", "t"]).
word(["n", "i", "x"]).
word(["n", "o", "a"]).
word(["n", "o", "b"]).
word(["n", "o", "d"]).
word(["n", "o", "g"]).
word(["n", "o", "n"]).
word(["n", "o", "r"]).
word(["n", "o", "t"]).
word(["N", "o", "u"]).
word(["n", "o", "w"]).
word(["n", "o", "y"]).
word(["n", "t", "h"]).
word(["n", "u", "b"]).
word(["n", "u", "l"]).
word(["n", "u", "n"]).
word(["n", "u", "t"]).
word(["n", "y", "e"]).
word(["o", "a", "f"]).
word(["o", "a", "k"]).
word(["o", "a", "m"]).
word(["o", "a", "r"]).
word(["o", "a", "t"]).
word(["o", "b", "e"]).
word(["o", "b", "i"]).
word(["o", "c", "h"]).
word(["o", "c", "k"]).
word(["o", "d", "a"]).
word(["o", "d", "d"]).
word(["o", "d", "e"]).
word(["O", "d", "s"]).
word(["O", "d", "z"]).
word(["o", "e", "r"]).
word(["o", "e", "s"]).
word(["o", "f", "f"]).
word(["O", "f", "o"]).
word(["o", "f", "t"]).
word(["o", "h", "m"]).
word(["o", "h", "o"]).
word(["o", "i", "i"]).
word(["o", "i", "l"]).
word(["o", "k", "a"]).
word(["o", "k", "i"]).
word(["O", "l", "d"]).
word(["o", "l", "d"]).
word(["O", "l", "e"]).
word(["o", "l", "m"]).
word(["O", "n", "a"]).
word(["o", "n", "a"]).
word(["o", "n", "e"]).
word(["o", "n", "s"]).
word(["o", "p", "e"]).
word(["o", "p", "t"]).
word(["o", "r", "a"]).
word(["o", "r", "b"]).
word(["o", "r", "c"]).
word(["o", "r", "e"]).
word(["o", "r", "f"]).
word(["o", "r", "t"]).
word(["o", "r", "y"]).
word(["O", "s", "c"]).
word(["o", "s", "e"]).
word(["O", "t", "o"]).
word(["o", "u", "f"]).
word(["o", "u", "r"]).
word(["o", "u", "t"]).
word(["O", "v", "a"]).
word(["o", "v", "a"]).
word(["o", "w", "d"]).
word(["o", "w", "e"]).
word(["o", "w", "k"]).
word(["o", "w", "l"]).
word(["o", "w", "n"]).
word(["o", "x", "y"]).
word(["p", "a", "c"]).
word(["p", "a", "d"]).
word(["p", "a", "h"]).
word(["p", "a", "l"]).
word(["P", "a", "m"]).
word(["p", "a", "m"]).
word(["P", "a", "n"]).
word(["p", "a", "n"]).
word(["p", "a", "p"]).
word(["p", "a", "r"]).
word(["P", "a", "t"]).
word(["p", "a", "t"]).
word(["p", "a", "u"]).
word(["p", "a", "w"]).
word(["p", "a", "x"]).
word(["p", "a", "y"]).
word(["p", "e", "a"]).
word(["p", "e", "d"]).
word(["p", "e", "e"]).
word(["P", "e", "g"]).
word(["p", "e", "g"]).
word(["p", "e", "n"]).
word(["p", "e", "p"]).
word(["P", "e", "r"]).
word(["p", "e", "r"]).
word(["p", "e", "s"]).
word(["p", "e", "t"]).
word(["p", "e", "w"]).
word(["p", "h", "i"]).
word(["p", "h", "o"]).
word(["p", "h", "u"]).
word(["P", "i", "a"]).
word(["p", "i", "a"]).
word(["p", "i", "c"]).
word(["p", "i", "e"]).
word(["p", "i", "g"]).
word(["p", "i", "k"]).
word(["P", "i", "m"]).
word(["p", "i", "n"]).
word(["p", "i", "p"]).
word(["p", "i", "r"]).
word(["p", "i", "t"]).
word(["p", "i", "x"]).
word(["p", "l", "y"]).
word(["P", "o", "a"]).
word(["p", "o", "b"]).
word(["p", "o", "d"]).
word(["p", "o", "e"]).
word(["p", "o", "h"]).
word(["p", "o", "i"]).
word(["p", "o", "l"]).
word(["p", "o", "m"]).
word(["p", "o", "n"]).
word(["P", "o", "p"]).
word(["p", "o", "p"]).
word(["p", "o", "t"]).
word(["p", "o", "w"]).
word(["p", "o", "x"]).
word(["p", "o", "y"]).
word(["p", "r", "o"]).
word(["p", "r", "y"]).
word(["p", "s", "i"]).
word(["p", "s", "t"]).
word(["p", "u", "a"]).
word(["p", "u", "b"]).
word(["p", "u", "d"]).
word(["p", "u", "g"]).
word(["p", "u", "l"]).
word(["p", "u", "n"]).
word(["p", "u", "p"]).
word(["p", "u", "r"]).
word(["p", "u", "s"]).
word(["p", "u", "t"]).
word(["p", "y", "a"]).
word(["p", "y", "r"]).
word(["p", "y", "x"]).
word(["q", "u", "a"]).
word(["q", "u", "o"]).
word(["R", "a", "b"]).
word(["r", "a", "b"]).
word(["r", "a", "d"]).
word(["r", "a", "g"]).
word(["r", "a", "h"]).
word(["R", "a", "j"]).
word(["r", "a", "j"]).
word(["R", "a", "m"]).
word(["r", "a", "m"]).
word(["R", "a", "n"]).
word(["r", "a", "n"]).
word(["r", "a", "p"]).
word(["r", "a", "s"]).
word(["r", "a", "t"]).
word(["r", "a", "w"]).
word(["r", "a", "x"]).
word(["R", "a", "y"]).
word(["r", "a", "y"]).
word(["r", "e", "a"]).
word(["r", "e", "b"]).
word(["R", "e", "d"]).
word(["r", "e", "d"]).
word(["R", "e", "e"]).
word(["r", "e", "e"]).
word(["r", "e", "f"]).
word(["r", "e", "g"]).
word(["r", "e", "h"]).
word(["r", "e", "l"]).
word(["r", "e", "p"]).
word(["r", "e", "t"]).
word(["r", "e", "v"]).
word(["R", "e", "x"]).
word(["r", "e", "x"]).
word(["r", "h", "e"]).
word(["r", "h", "o"]).
word(["r", "i", "a"]).
word(["r", "i", "b"]).
word(["R", "i", "c"]).
word(["r", "i", "d"]).
word(["r", "i", "e"]).
word(["r", "i", "g"]).
word(["R", "i", "k"]).
word(["r", "i", "m"]).
word(["R", "i", "o"]).
word(["r", "i", "o"]).
word(["r", "i", "p"]).
word(["r", "i", "t"]).
word(["r", "i", "x"]).
word(["R", "o", "b"]).
word(["r", "o", "b"]).
word(["r", "o", "c"]).
word(["R", "o", "d"]).
word(["r", "o", "d"]).
word(["r", "o", "e"]).
word(["r", "o", "g"]).
word(["r", "o", "i"]).
word(["R", "o", "k"]).
word(["R", "o", "n"]).
word(["r", "o", "t"]).
word(["r", "o", "w"]).
word(["r", "o", "x"]).
word(["R", "o", "y"]).
word(["R", "u", "a"]).
word(["r", "u", "b"]).
word(["r", "u", "d"]).
word(["r", "u", "e"]).
word(["r", "u", "g"]).
word(["R", "u", "m"]).
word(["r", "u", "m"]).
word(["r", "u", "n"]).
word(["R", "u", "s"]).
word(["r", "u", "t"]).
word(["r", "u", "x"]).
word(["r", "y", "e"]).
word(["s", "a", "a"]).
word(["s", "a", "b"]).
word(["S", "a", "c"]).
word(["s", "a", "c"]).
word(["s", "a", "d"]).
word(["s", "a", "g"]).
word(["s", "a", "h"]).
word(["s", "a", "i"]).
word(["s", "a", "j"]).
word(["S", "a", "k"]).
word(["S", "a", "l"]).
word(["s", "a", "l"]).
word(["S", "a", "m"]).
word(["s", "a", "m"]).
word(["S", "a", "n"]).
word(["s", "a", "n"]).
word(["s", "a", "o"]).
word(["s", "a", "p"]).
word(["s", "a", "r"]).
word(["s", "a", "t"]).
word(["s", "a", "w"]).
word(["s", "a", "x"]).
word(["s", "a", "y"]).
word(["s", "e", "a"]).
word(["s", "e", "c"]).
word(["s", "e", "e"]).
word(["s", "e", "g"]).
word(["s", "e", "n"]).
word(["s", "e", "r"]).
word(["s", "e", "t"]).
word(["s", "e", "w"]).
word(["s", "e", "x"]).
word(["s", "e", "y"]).
word(["s", "h", "a"]).
word(["s", "h", "e"]).
word(["s", "h", "i"]).
word(["S", "h", "o"]).
word(["s", "h", "o"]).
word(["S", "h", "u"]).
word(["s", "h", "y"]).
word(["S", "i", "a"]).
word(["s", "i", "b"]).
word(["s", "i", "c"]).
word(["S", "i", "d"]).
word(["s", "i", "e"]).
word(["s", "i", "g"]).
word(["s", "i", "l"]).
word(["S", "i", "m"]).
word(["s", "i", "n"]).
word(["s", "i", "p"]).
word(["S", "i", "r"]).
word(["s", "i", "r"]).
word(["S", "i", "s"]).
word(["s", "i", "s"]).
word(["s", "i", "t"]).
word(["s", "i", "x"]).
word(["s", "k", "i"]).
word(["s", "k", "y"]).
word(["s", "l", "a"]).
word(["s", "l", "y"]).
word(["s", "m", "a"]).
word(["s", "n", "y"]).
word(["s", "o", "b"]).
word(["s", "o", "c"]).
word(["s", "o", "d"]).
word(["s", "o", "e"]).
word(["s", "o", "g"]).
word(["s", "o", "h"]).
word(["s", "o", "k"]).
word(["S", "o", "l"]).
word(["s", "o", "l"]).
word(["S", "o", "n"]).
word(["s", "o", "n"]).
word(["s", "o", "p"]).
word(["s", "o", "t"]).
word(["s", "o", "u"]).
word(["s", "o", "v"]).
word(["s", "o", "w"]).
word(["s", "o", "y"]).
word(["s", "p", "a"]).
word(["S", "p", "y"]).
word(["s", "p", "y"]).
word(["S", "r", "i"]).
word(["s", "r", "i"]).
word(["S", "s", "i"]).
word(["s", "s", "u"]).
word(["S", "t", "u"]).
word(["s", "t", "y"]).
word(["s", "u", "b"]).
word(["s", "u", "d"]).
word(["S", "u", "e"]).
word(["s", "u", "e"]).
word(["S", "u", "i"]).
word(["S", "u", "k"]).
word(["s", "u", "m"]).
word(["s", "u", "n"]).
word(["s", "u", "p"]).
word(["s", "u", "r"]).
word(["S", "u", "s"]).
word(["S", "u", "u"]).
word(["s", "u", "z"]).
word(["s", "w", "a"]).
word(["S", "y", "d"]).
word(["s", "y", "e"]).
word(["t", "a", "a"]).
word(["T", "a", "b"]).
word(["t", "a", "b"]).
word(["T", "a", "d"]).
word(["t", "a", "d"]).
word(["t", "a", "e"]).
word(["t", "a", "g"]).
word(["T", "a", "i"]).
word(["t", "a", "i"]).
word(["t", "a", "j"]).
word(["T", "a", "l"]).
word(["t", "a", "l"]).
word(["t", "a", "m"]).
word(["t", "a", "n"]).
word(["T", "a", "o"]).
word(["t", "a", "o"]).
word(["t", "a", "p"]).
word(["t", "a", "r"]).
word(["T", "a", "t"]).
word(["t", "a", "t"]).
word(["t", "a", "u"]).
word(["t", "a", "v"]).
word(["t", "a", "w"]).
word(["t", "a", "x"]).
word(["t", "a", "y"]).
word(["t", "c", "h"]).
word(["t", "c", "k"]).
word(["t", "e", "a"]).
word(["t", "e", "c"]).
word(["T", "e", "d"]).
word(["t", "e", "d"]).
word(["t", "e", "e"]).
word(["t", "e", "g"]).
word(["t", "e", "n"]).
word(["t", "e", "w"]).
word(["t", "e", "z"]).
word(["t", "h", "a"]).
word(["T", "h", "e"]).
word(["t", "h", "e"]).
word(["T", "h", "o"]).
word(["t", "h", "o"]).
word(["t", "h", "y"]).
word(["t", "i", "b"]).
word(["t", "i", "c"]).
word(["t", "i", "d"]).
word(["t", "i", "e"]).
word(["t", "i", "g"]).
word(["t", "i", "l"]).
word(["T", "i", "m"]).
word(["t", "i", "n"]).
word(["t", "i", "p"]).
word(["t", "i", "t"]).
word(["t", "j", "i"]).
word(["t", "o", "a"]).
word(["T", "o", "d"]).
word(["t", "o", "d"]).
word(["t", "o", "e"]).
word(["t", "o", "g"]).
word(["t", "o", "i"]).
word(["t", "o", "l"]).
word(["T", "o", "m"]).
word(["t", "o", "n"]).
word(["t", "o", "o"]).
word(["t", "o", "p"]).
word(["T", "o", "r"]).
word(["t", "o", "r"]).
word(["t", "o", "t"]).
word(["t", "o", "u"]).
word(["t", "o", "w"]).
word(["t", "o", "x"]).
word(["t", "o", "y"]).
word(["t", "r", "a"]).
word(["t", "r", "i"]).
word(["t", "r", "y"]).
word(["t", "s", "t"]).
word(["t", "u", "a"]).
word(["t", "u", "b"]).
word(["t", "u", "e"]).
word(["t", "u", "g"]).
word(["t", "u", "i"]).
word(["t", "u", "m"]).
word(["t", "u", "n"]).
word(["t", "u", "p"]).
word(["t", "u", "r"]).
word(["t", "u", "t"]).
word(["t", "u", "x"]).
word(["t", "w", "a"]).
word(["T", "w", "i"]).
word(["t", "w", "o"]).
word(["t", "y", "e"]).
word(["t", "y", "g"]).
word(["t", "y", "t"]).
word(["u", "b", "i"]).
word(["U", "c", "a"]).
word(["U", "d", "i"]).
word(["u", "d", "o"]).
word(["U", "d", "s"]).
word(["u", "g", "h"]).
word(["u", "j", "i"]).
word(["u", "k", "e"]).
word(["u", "l", "a"]).
word(["u", "l", "e"]).
word(["u", "l", "l"]).
word(["u", "l", "u"]).
word(["u", "m", "e"]).
word(["u", "m", "p"]).
word(["u", "m", "u"]).
word(["U", "n", "a"]).
word(["u", "p", "o"]).
word(["u", "r", "a"]).
word(["u", "r", "d"]).
word(["u", "r", "e"]).
word(["u", "r", "f"]).
word(["U", "r", "i"]).
word(["u", "r", "n"]).
word(["U", "r", "o"]).
word(["U", "r", "s"]).
word(["U", "r", "u"]).
word(["u", "s", "e"]).
word(["u", "s", "h"]).
word(["u", "s", "t"]).
word(["U", "t", "a"]).
word(["u", "t", "a"]).
word(["U", "t", "e"]).
word(["u", "t", "u"]).
word(["u", "v", "a"]).
word(["v", "a", "g"]).
word(["V", "a", "i"]).
word(["V", "a", "l"]).
word(["V", "a", "n"]).
word(["v", "a", "n"]).
word(["v", "a", "s"]).
word(["v", "a", "t"]).
word(["v", "a", "u"]).
word(["v", "e", "e"]).
word(["v", "e", "i"]).
word(["v", "e", "t"]).
word(["v", "e", "x"]).
word(["v", "i", "a"]).
word(["V", "i", "c"]).
word(["v", "i", "e"]).
word(["v", "i", "m"]).
word(["V", "i", "p"]).
word(["v", "i", "s"]).
word(["V", "o", "d"]).
word(["v", "o", "e"]).
word(["v", "o", "g"]).
word(["v", "o", "l"]).
word(["v", "o", "w"]).
word(["v", "u", "g"]).
word(["v", "u", "m"]).
word(["w", "a", "b"]).
word(["W", "a", "c"]).
word(["w", "a", "d"]).
word(["w", "a", "e"]).
word(["W", "a", "f"]).
word(["w", "a", "g"]).
word(["w", "a", "h"]).
word(["w", "a", "n"]).
word(["w", "a", "p"]).
word(["w", "a", "r"]).
word(["w", "a", "s"]).
word(["W", "a", "t"]).
word(["w", "a", "t"]).
word(["w", "a", "w"]).
word(["w", "a", "x"]).
word(["w", "a", "y"]).
word(["W", "e", "a"]).
word(["w", "e", "b"]).
word(["w", "e", "d"]).
word(["w", "e", "e"]).
word(["W", "e", "i"]).
word(["w", "e", "m"]).
word(["w", "e", "n"]).
word(["w", "e", "r"]).
word(["W", "e", "s"]).
word(["w", "e", "t"]).
word(["w", "e", "y"]).
word(["w", "h", "a"]).
word(["w", "h", "o"]).
word(["w", "h", "y"]).
word(["w", "i", "d"]).
word(["w", "i", "g"]).
word(["w", "i", "m"]).
word(["W", "i", "n"]).
word(["w", "i", "n"]).
word(["w", "i", "r"]).
word(["w", "i", "s"]).
word(["w", "i", "t"]).
word(["w", "i", "z"]).
word(["w", "o", "b"]).
word(["w", "o", "d"]).
word(["w", "o", "e"]).
word(["w", "o", "g"]).
word(["w", "o", "n"]).
word(["w", "o", "o"]).
word(["w", "o", "p"]).
word(["w", "o", "t"]).
word(["w", "o", "w"]).
word(["w", "o", "y"]).
word(["w", "r", "o"]).
word(["w", "r", "y"]).
word(["w", "u", "d"]).
word(["w", "u", "n"]).
word(["w", "u", "p"]).
word(["w", "u", "r"]).
word(["w", "u", "t"]).
word(["w", "y", "e"]).
word(["w", "y", "n"]).
word(["y", "a", "d"]).
word(["y", "a", "h"]).
word(["y", "a", "k"]).
word(["y", "a", "m"]).
word(["y", "a", "n"]).
word(["Y", "a", "o"]).
word(["y", "a", "p"]).
word(["y", "a", "r"]).
word(["y", "a", "s"]).
word(["y", "a", "t"]).
word(["y", "a", "w"]).
word(["y", "e", "a"]).
word(["y", "e", "d"]).
word(["y", "e", "e"]).
word(["y", "e", "n"]).
word(["y", "e", "o"]).
word(["y", "e", "p"]).
word(["y", "e", "r"]).
word(["y", "e", "s"]).
word(["y", "e", "t"]).
word(["y", "e", "w"]).
word(["y", "e", "x"]).
word(["y", "e", "z"]).
word(["Y", "i", "d"]).
word(["Y", "i", "n"]).
word(["y", "i", "n"]).
word(["y", "i", "p"]).
word(["y", "i", "s"]).
word(["y", "o", "e"]).
word(["y", "o", "i"]).
word(["y", "o", "k"]).
word(["y", "o", "m"]).
word(["y", "o", "n"]).
word(["y", "o", "r"]).
word(["y", "o", "t"]).
word(["y", "o", "u"]).
word(["y", "o", "w"]).
word(["y", "o", "x"]).
word(["y", "o", "y"]).
word(["y", "u", "h"]).
word(["Y", "u", "n"]).
word(["y", "u", "s"]).
word(["z", "a", "c"]).
word(["z", "a", "d"]).
word(["z", "a", "g"]).
word(["z", "a", "k"]).
word(["Z", "a", "n"]).
word(["z", "a", "r"]).
word(["z", "a", "t"]).
word(["z", "a", "x"]).
word(["Z", "e", "a"]).
word(["z", "e", "d"]).
word(["z", "e", "e"]).
word(["z", "e", "l"]).
word(["Z", "e", "n"]).
word(["Z", "e", "p"]).
word(["z", "e", "r"]).
word(["z", "i", "g"]).
word(["z", "i", "p"]).
word(["Z", "o", "a"]).
word(["z", "o", "a"]).
word(["z", "o", "o"]).
