word(["a", "b", "l", "e"]).
word(["a", "c", "i", "d"]).
word(["a", "i", "d", "e"]).
word(["a", "l", "l", "y"]).
word(["a", "l", "s", "o"]).
word(["a", "r", "e", "a"]).
word(["a", "r", "m", "y"]).
word(["a", "u", "t", "o"]).
word(["a", "w", "a", "y"]).
word(["b", "a", "b", "y"]).
word(["b", "a", "c", "k"]).
word(["b", "a", "k", "e"]).
word(["b", "a", "l", "l"]).
word(["b", "a", "n", "d"]).
word(["b", "a", "n", "k"]).
word(["b", "a", "s", "e"]).
word(["b", "e", "a", "n"]).
word(["b", "e", "a", "r"]).
word(["b", "e", "a", "t"]).
word(["b", "e", "e", "r"]).
word(["b", "e", "l", "l"]).
word(["b", "e", "l", "t"]).
word(["b", "e", "n", "d"]).
word(["b", "e", "s", "t"]).
word(["b", "i", "k", "e"]).
word(["b", "i", "l", "l"]).
word(["b", "i", "n", "d"]).
word(["b", "i", "r", "d"]).
word(["b", "i", "t", "e"]).
word(["b", "l", "o", "w"]).
word(["b", "l", "u", "e"]).
word(["b", "o", "a", "t"]).
word(["b", "o", "d", "y"]).
word(["b", "o", "m", "b"]).
word(["b", "o", "n", "d"]).
word(["b", "o", "n", "e"]).
word(["b", "o", "o", "k"]).
word(["b", "o", "o", "m"]).
word(["b", "o", "o", "t"]).
word(["b", "o", "r", "n"]).
word(["b", "o", "s", "s"]).
word(["b", "o", "t", "h"]).
word(["b", "o", "w", "l"]).
word(["b", "u", "c", "k"]).
word(["b", "u", "r", "n"]).
word(["b", "u", "r", "y"]).
word(["b", "u", "s", "y"]).
word(["c", "a", "k", "e"]).
word(["c", "a", "l", "l"]).
word(["c", "a", "m", "p"]).
word(["c", "a", "r", "d"]).
word(["c", "a", "r", "e"]).
word(["c", "a", "s", "e"]).
word(["c", "a", "s", "h"]).
word(["c", "a", "s", "t"]).
word(["c", "e", "l", "l"]).
word(["c", "h", "e", "f"]).
word(["c", "h", "i", "p"]).
word(["c", "i", "t", "e"]).
word(["c", "i", "t", "y"]).
word(["c", "l", "u", "b"]).
word(["c", "l", "u", "e"]).
word(["c", "o", "a", "l"]).
word(["c", "o", "a", "t"]).
word(["c", "o", "d", "e"]).
word(["c", "o", "l", "d"]).
word(["c", "o", "m", "e"]).
word(["c", "o", "o", "k"]).
word(["c", "o", "o", "l"]).
word(["c", "o", "p", "e"]).
word(["c", "o", "p", "y"]).
word(["c", "o", "r", "e"]).
word(["c", "o", "r", "n"]).
word(["c", "o", "s", "t"]).
word(["c", "r", "e", "w"]).
word(["c", "r", "o", "p"]).
word(["d", "a", "r", "e"]).
word(["d", "a", "r", "k"]).
word(["d", "a", "t", "a"]).
word(["d", "a", "t", "e"]).
word(["d", "e", "a", "d"]).
word(["d", "e", "a", "l"]).
word(["d", "e", "a", "r"]).
word(["d", "e", "b", "t"]).
word(["d", "e", "c", "k"]).
word(["d", "e", "e", "p"]).
word(["d", "e", "e", "r"]).
word(["d", "e", "n", "y"]).
word(["d", "e", "s", "k"]).
word(["d", "i", "e", "t"]).
word(["d", "i", "r", "t"]).
word(["d", "i", "s", "h"]).
word(["d", "o", "o", "r"]).
word(["d", "o", "w", "n"]).
word(["d", "r", "a", "g"]).
word(["d", "r", "a", "w"]).
word(["d", "r", "o", "p"]).
word(["d", "r", "u", "g"]).
word(["d", "u", "s", "t"]).
word(["d", "u", "t", "y"]).
word(["e", "a", "c", "h"]).
word(["e", "a", "r", "n"]).
word(["e", "a", "s", "e"]).
word(["e", "a", "s", "t"]).
word(["e", "a", "s", "y"]).
word(["e", "d", "g", "e"]).
word(["e", "l", "s", "e"]).
word(["e", "v", "e", "n"]).
word(["e", "v", "e", "r"]).
word(["f", "a", "c", "e"]).
word(["f", "a", "c", "t"]).
word(["f", "a", "d", "e"]).
word(["f", "a", "i", "l"]).
word(["f", "a", "i", "r"]).
word(["f", "a", "l", "l"]).
word(["f", "a", "r", "m"]).
word(["f", "a", "s", "t"]).
word(["f", "a", "t", "e"]).
word(["f", "e", "a", "r"]).
word(["f", "e", "e", "d"]).
word(["f", "e", "e", "l"]).
word(["f", "i", "l", "e"]).
word(["f", "i", "l", "l"]).
word(["f", "i", "l", "m"]).
word(["f", "i", "n", "d"]).
word(["f", "i", "n", "e"]).
word(["f", "i", "r", "e"]).
word(["f", "i", "r", "m"]).
word(["f", "i", "s", "h"]).
word(["f", "i", "v", "e"]).
word(["f", "l", "a", "g"]).
word(["f", "l", "a", "t"]).
word(["f", "l", "e", "e"]).
word(["f", "l", "o", "w"]).
word(["f", "o", "l", "k"]).
word(["f", "o", "o", "d"]).
word(["f", "o", "o", "t"]).
word(["f", "o", "r", "m"]).
word(["f", "o", "u", "r"]).
word(["f", "r", "e", "e"]).
word(["f", "r", "o", "m"]).
word(["f", "u", "e", "l"]).
word(["f", "u", "l", "l"]).
word(["f", "u", "n", "d"]).
word(["g", "a", "i", "n"]).
word(["g", "a", "m", "e"]).
word(["g", "a", "n", "g"]).
word(["g", "a", "t", "e"]).
word(["g", "a", "z", "e"]).
word(["g", "e", "a", "r"]).
word(["g", "e", "n", "e"]).
word(["g", "i", "f", "t"]).
word(["g", "i", "r", "l"]).
word(["g", "i", "v", "e"]).
word(["g", "l", "a", "d"]).
word(["g", "o", "a", "l"]).
word(["g", "o", "l", "d"]).
word(["g", "o", "l", "f"]).
word(["g", "o", "o", "d"]).
word(["g", "r", "a", "b"]).
word(["g", "r", "a", "y"]).
word(["g", "r", "o", "w"]).
word(["h", "a", "i", "r"]).
word(["h", "a", "l", "f"]).
word(["h", "a", "l", "l"]).
word(["h", "a", "n", "d"]).
word(["h", "a", "n", "g"]).
word(["h", "a", "r", "d"]).
word(["h", "a", "t", "e"]).
word(["h", "a", "v", "e"]).
word(["h", "e", "a", "d"]).
word(["h", "e", "a", "r"]).
word(["h", "e", "a", "t"]).
word(["h", "e", "e", "l"]).
word(["h", "e", "l", "l"]).
word(["h", "e", "l", "p"]).
word(["h", "e", "r", "e"]).
word(["h", "e", "r", "o"]).
word(["h", "i", "d", "e"]).
word(["h", "i", "g", "h"]).
word(["h", "i", "l", "l"]).
word(["h", "i", "r", "e"]).
word(["h", "o", "l", "d"]).
word(["h", "o", "l", "e"]).
word(["h", "o", "l", "y"]).
word(["h", "o", "m", "e"]).
word(["h", "o", "p", "e"]).
word(["h", "o", "s", "t"]).
word(["h", "o", "u", "r"]).
word(["h", "u", "g", "e"]).
word(["h", "u", "r", "t"]).
word(["i", "d", "e", "a"]).
word(["i", "n", "t", "o"]).
word(["i", "r", "o", "n"]).
word(["i", "t", "e", "m"]).
word(["j", "a", "i", "l"]).
word(["j", "o", "i", "n"]).
word(["j", "o", "k", "e"]).
word(["j", "u", "m", "p"]).
word(["j", "u", "r", "y"]).
word(["j", "u", "s", "t"]).
word(["k", "e", "e", "p"]).
word(["k", "i", "c", "k"]).
word(["k", "i", "l", "l"]).
word(["k", "i", "n", "d"]).
word(["k", "i", "n", "g"]).
word(["k", "i", "s", "s"]).
word(["k", "n", "e", "e"]).
word(["k", "n", "o", "w"]).
word(["l", "a", "c", "k"]).
word(["l", "a", "d", "y"]).
word(["l", "a", "k", "e"]).
word(["l", "a", "n", "d"]).
word(["l", "a", "s", "t"]).
word(["l", "a", "t", "e"]).
word(["l", "a", "w", "n"]).
word(["l", "e", "a", "d"]).
word(["l", "e", "a", "f"]).
word(["l", "e", "a", "n"]).
word(["l", "e", "f", "t"]).
word(["l", "e", "s", "s"]).
word(["l", "i", "f", "e"]).
word(["l", "i", "f", "t"]).
word(["l", "i", "k", "e"]).
word(["l", "i", "n", "e"]).
word(["l", "i", "n", "k"]).
word(["l", "i", "s", "t"]).
word(["l", "i", "v", "e"]).
word(["l", "o", "a", "d"]).
word(["l", "o", "a", "n"]).
word(["l", "o", "c", "k"]).
word(["l", "o", "n", "g"]).
word(["l", "o", "o", "k"]).
word(["l", "o", "s", "e"]).
word(["l", "o", "s", "s"]).
word(["l", "o", "s", "t"]).
word(["l", "o", "t", "s"]).
word(["l", "o", "u", "d"]).
word(["l", "o", "v", "e"]).
word(["l", "u", "c", "k"]).
word(["l", "u", "n", "g"]).
word(["m", "a", "i", "l"]).
word(["m", "a", "i", "n"]).
word(["m", "a", "k", "e"]).
word(["m", "a", "l", "e"]).
word(["m", "a", "l", "l"]).
word(["m", "a", "n", "y"]).
word(["m", "a", "r", "k"]).
word(["m", "a", "s", "k"]).
word(["m", "a", "s", "s"]).
word(["m", "a", "t", "h"]).
word(["m", "e", "a", "l"]).
word(["m", "e", "a", "n"]).
word(["m", "e", "a", "t"]).
word(["m", "e", "e", "t"]).
word(["m", "e", "n", "u"]).
word(["m", "e", "r", "e"]).
word(["m", "e", "s", "s"]).
word(["m", "i", "l", "k"]).
word(["m", "i", "n", "d"]).
word(["m", "i", "n", "e"]).
word(["m", "i", "s", "s"]).
word(["m", "o", "d", "e"]).
word(["m", "o", "o", "d"]).
word(["m", "o", "o", "n"]).
word(["m", "o", "r", "e"]).
word(["m", "o", "s", "t"]).
word(["m", "o", "v", "e"]).
word(["m", "u", "c", "h"]).
word(["m", "u", "s", "t"]).
word(["m", "y", "t", "h"]).
word(["n", "a", "m", "e"]).
word(["n", "e", "a", "r"]).
word(["n", "e", "c", "k"]).
word(["n", "e", "e", "d"]).
word(["n", "e", "w", "s"]).
word(["n", "e", "x", "t"]).
word(["n", "i", "c", "e"]).
word(["n", "i", "n", "e"]).
word(["n", "o", "n", "e"]).
word(["n", "o", "s", "e"]).
word(["n", "o", "t", "e"]).
word(["o", "d", "d", "s"]).
word(["o", "k", "a", "y"]).
word(["o", "n", "c", "e"]).
word(["o", "n", "l", "y"]).
word(["o", "n", "t", "o"]).
word(["o", "p", "e", "n"]).
word(["o", "v", "e", "n"]).
word(["o", "v", "e", "r"]).
word(["p", "a", "c", "e"]).
word(["p", "a", "c", "k"]).
word(["p", "a", "g", "e"]).
word(["p", "a", "i", "n"]).
word(["p", "a", "i", "r"]).
word(["p", "a", "l", "e"]).
word(["p", "a", "l", "m"]).
word(["p", "a", "n", "t"]).
word(["p", "a", "r", "k"]).
word(["p", "a", "r", "t"]).
word(["p", "a", "s", "s"]).
word(["p", "a", "s", "t"]).
word(["p", "a", "t", "h"]).
word(["p", "e", "a", "k"]).
word(["p", "e", "e", "r"]).
word(["p", "i", "c", "k"]).
word(["p", "i", "l", "e"]).
word(["p", "i", "n", "e"]).
word(["p", "i", "n", "k"]).
word(["p", "i", "p", "e"]).
word(["p", "l", "a", "n"]).
word(["p", "l", "a", "y"]).
word(["p", "l", "o", "t"]).
word(["p", "l", "u", "s"]).
word(["p", "o", "e", "m"]).
word(["p", "o", "e", "t"]).
word(["p", "o", "l", "e"]).
word(["p", "o", "l", "l"]).
word(["p", "o", "o", "l"]).
word(["p", "o", "o", "r"]).
word(["p", "o", "r", "t"]).
word(["p", "o", "s", "e"]).
word(["p", "o", "s", "t"]).
word(["p", "o", "u", "r"]).
word(["p", "r", "a", "y"]).
word(["p", "u", "l", "l"]).
word(["p", "u", "r", "e"]).
word(["p", "u", "s", "h"]).
word(["q", "u", "i", "t"]).
word(["r", "a", "c", "e"]).
word(["r", "a", "i", "l"]).
word(["r", "a", "i", "n"]).
word(["r", "a", "n", "k"]).
word(["r", "a", "r", "e"]).
word(["r", "a", "t", "e"]).
word(["r", "e", "a", "d"]).
word(["r", "e", "a", "l"]).
word(["r", "e", "l", "y"]).
word(["r", "e", "s", "t"]).
word(["r", "i", "c", "e"]).
word(["r", "i", "c", "h"]).
word(["r", "i", "d", "e"]).
word(["r", "i", "n", "g"]).
word(["r", "i", "s", "e"]).
word(["r", "i", "s", "k"]).
word(["r", "o", "a", "d"]).
word(["r", "o", "c", "k"]).
word(["r", "o", "l", "e"]).
word(["r", "o", "l", "l"]).
word(["r", "o", "o", "f"]).
word(["r", "o", "o", "m"]).
word(["r", "o", "o", "t"]).
word(["r", "o", "p", "e"]).
word(["r", "o", "s", "e"]).
word(["r", "u", "l", "e"]).
word(["r", "u", "s", "h"]).
word(["s", "a", "f", "e"]).
word(["s", "a", "k", "e"]).
word(["s", "a", "l", "e"]).
word(["s", "a", "l", "t"]).
word(["s", "a", "m", "e"]).
word(["s", "a", "n", "d"]).
word(["s", "a", "v", "e"]).
word(["s", "e", "a", "t"]).
word(["s", "e", "e", "d"]).
word(["s", "e", "e", "k"]).
word(["s", "e", "e", "m"]).
word(["s", "e", "l", "f"]).
word(["s", "e", "l", "l"]).
word(["s", "e", "n", "d"]).
word(["s", "h", "i", "p"]).
word(["s", "h", "i", "t"]).
word(["s", "h", "o", "e"]).
word(["s", "h", "o", "p"]).
word(["s", "h", "o", "t"]).
word(["s", "h", "o", "w"]).
word(["s", "h", "u", "t"]).
word(["s", "i", "c", "k"]).
word(["s", "i", "d", "e"]).
word(["s", "i", "g", "h"]).
word(["s", "i", "g", "n"]).
word(["s", "i", "n", "g"]).
word(["s", "i", "n", "k"]).
word(["s", "i", "t", "e"]).
word(["s", "i", "z", "e"]).
word(["s", "k", "i", "n"]).
word(["s", "l", "i", "p"]).
word(["s", "l", "o", "w"]).
word(["s", "n", "a", "p"]).
word(["s", "n", "o", "w"]).
word(["s", "o", "f", "t"]).
word(["s", "o", "i", "l"]).
word(["s", "o", "m", "e"]).
word(["s", "o", "n", "g"]).
word(["s", "o", "o", "n"]).
word(["s", "o", "r", "t"]).
word(["s", "o", "u", "l"]).
word(["s", "o", "u", "p"]).
word(["s", "p", "i", "n"]).
word(["s", "p", "o", "t"]).
word(["s", "t", "a", "r"]).
word(["s", "t", "a", "y"]).
word(["s", "t", "e", "p"]).
word(["s", "t", "i", "r"]).
word(["s", "t", "o", "p"]).
word(["s", "u", "c", "h"]).
word(["s", "u", "i", "t"]).
word(["s", "u", "r", "e"]).
word(["s", "w", "i", "m"]).
word(["t", "a", "i", "l"]).
word(["t", "a", "k", "e"]).
word(["t", "a", "l", "e"]).
word(["t", "a", "l", "k"]).
word(["t", "a", "l", "l"]).
word(["t", "a", "n", "k"]).
word(["t", "a", "p", "e"]).
word(["t", "a", "s", "k"]).
word(["t", "e", "a", "m"]).
word(["t", "e", "a", "r"]).
word(["t", "e", "e", "n"]).
word(["t", "e", "l", "l"]).
word(["t", "e", "n", "d"]).
word(["t", "e", "n", "t"]).
word(["t", "e", "r", "m"]).
word(["t", "e", "s", "t"]).
word(["t", "e", "x", "t"]).
word(["t", "h", "a", "n"]).
word(["t", "h", "a", "t"]).
word(["t", "h", "e", "m"]).
word(["t", "h", "e", "n"]).
word(["t", "h", "e", "y"]).
word(["t", "h", "i", "n"]).
word(["t", "h", "i", "s"]).
word(["t", "h", "u", "s"]).
word(["t", "i", "m", "e"]).
word(["t", "i", "n", "y"]).
word(["t", "i", "r", "e"]).
word(["t", "o", "n", "e"]).
word(["t", "o", "o", "l"]).
word(["t", "o", "s", "s"]).
word(["t", "o", "u", "r"]).
word(["t", "o", "w", "n"]).
word(["t", "r", "e", "e"]).
word(["t", "r", "i", "p"]).
word(["t", "r", "u", "e"]).
word(["t", "u", "b", "e"]).
word(["t", "u", "r", "n"]).
word(["t", "w", "i", "n"]).
word(["t", "y", "p", "e"]).
word(["u", "g", "l", "y"]).
word(["u", "n", "i", "t"]).
word(["u", "p", "o", "n"]).
word(["u", "r", "g", "e"]).
word(["u", "s", "e", "d"]).
word(["u", "s", "e", "r"]).
word(["v", "a", "r", "y"]).
word(["v", "a", "s", "t"]).
word(["v", "e", "r", "y"]).
word(["v", "i", "e", "w"]).
word(["v", "o", "t", "e"]).
word(["w", "a", "g", "e"]).
word(["w", "a", "i", "t"]).
word(["w", "a", "k", "e"]).
word(["w", "a", "l", "k"]).
word(["w", "a", "l", "l"]).
word(["w", "a", "n", "t"]).
word(["w", "a", "r", "m"]).
word(["w", "a", "r", "n"]).
word(["w", "a", "s", "h"]).
word(["w", "a", "v", "e"]).
word(["w", "e", "a", "k"]).
word(["w", "e", "a", "r"]).
word(["w", "e", "e", "k"]).
word(["w", "e", "l", "l"]).
word(["w", "e", "s", "t"]).
word(["w", "h", "a", "t"]).
word(["w", "h", "e", "n"]).
word(["w", "h", "o", "m"]).
word(["w", "i", "d", "e"]).
word(["w", "i", "f", "e"]).
word(["w", "i", "l", "d"]).
word(["w", "i", "l", "l"]).
word(["w", "i", "n", "d"]).
word(["w", "i", "n", "e"]).
word(["w", "i", "n", "g"]).
word(["w", "i", "p", "e"]).
word(["w", "i", "r", "e"]).
word(["w", "i", "s", "e"]).
word(["w", "i", "s", "h"]).
word(["w", "i", "t", "h"]).
word(["w", "o", "o", "d"]).
word(["w", "o", "r", "d"]).
word(["w", "o", "r", "k"]).
word(["w", "r", "a", "p"]).
word(["y", "a", "r", "d"]).
word(["y", "e", "a", "h"]).
word(["y", "e", "a", "r"]).
word(["y", "e", "l", "l"]).
word(["y", "o", "u", "r"]).
word(["z", "o", "n", "e"]).
